[supabase]
url = "https://wtraxrmhlvagmrmcmgmd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cmF4cm1obHZhZ21ybWNtZ21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MzU0ODksImV4cCI6MjA3ODMxMTQ4OX0.FaglKSdq0yxZYsIfCczvERJU4VUhEOSmPW9n1-4U4uo" 
